_schema: _schema
paths:
  uploads: static/uploads
  static: static
collections_config:
  en:
    path: blog/en
    name: En
    icon: ent
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  fr:
    path: blog/fr
    name: Fr
    icon: 1k
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  gr:
    path: blog/gr
    name: Gr
    icon: 1k
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  nl:
    path: blog/nl
    name: Nl
    icon: 1k
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  galerie/fr:
    path:
    glob:
      - '*.md'
    name:
    singular_name:
    icon: notes
    url:
    disable_url: true
    include_developer_files:
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Europe/Brussels
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
